Created Editor folder under Scripts, moved AutomatedTesting.cs there
Ran into an error in Unity:

Assets\QuickChange\Scripts\Game\AutomatedTesting.cs(4,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)

Resolved it by moving the automated testing file to it's own folder to ensure that the NUnit tests run only within the Unity Editor.